// let addition:number= 3+5;
// console.log(" 3 + 5 = ",addition);
// let subtraction :number= 16 - 8;
// console.log(" 16 - 8 = ",subtraction);
// let multiplication :number = 4 * 2;
// console.log(" 4 * 2 = ",multiplication);
// let division : number = 16 / 2;
// console.log(" 16 / 2 = ",division);
console.log(5 + 3);
console.log(16 - 8);
console.log(4 * 2);
console.log(64 / 8);
